# lattice dns/ip (without `https://` protocol prefix)
lattice-ip: <LATTICE DNS/IP>
# lattice-bearer-token
lattice-bearer-token: <LATTICE BEARER TOKEN>
# asset latitude and longitude
latitude: 1
longitude: 1